"""tabla de valores en seguimiento

Revision ID: 1fedfba2a876
Revises: c4787b48e06a
Create Date: 2026-07-31 18:03:06.076073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fedfba2a876'
down_revision: Union[str, None] = 'c4787b48e06a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('asset_type', sa.Enum('cuenta_bancaria', 'accion_etf_fondo', 'criptomoneda', 'inmueble_otro', name='assettype'), nullable=False),
    sa.Column('currency', sa.Enum('EUR', 'USD', 'AUD', 'BGN', 'BRL', 'CAD', 'CHF', 'CNY', 'CZK', 'DKK', 'GBP', 'HKD', 'HUF', 'IDR', 'ILS', 'INR', 'ISK', 'JPY', 'KRW', 'MXN', 'MYR', 'NOK', 'NZD', 'PHP', 'PLN', 'RON', 'SEK', 'SGD', 'THB', 'TRY', 'ZAR', name='currency'), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('previous_close', sa.Float(), nullable=True),
    sa.Column('last_price_update', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist')
    # ### end Alembic commands ###
