"""importes del libro a Numeric

Pasa a Numeric(12,2) los importes que se suman (gastos, ingresos, presupuestos):
con Float, diez gastos de 0,10 € sumaban 0.9999999999999999 y el error se
arrastraba a los totales del mes.

Los precios y cantidades de la cartera siguen en Float a propósito: son
valoraciones a mercado alimentadas por floats de Yahoo/CoinGecko/Frankfurter.

SQLite no tiene tipo decimal nativo, así que el valor se guarda como REAL y
SQLAlchemy lo cuadra a 2 decimales al leerlo; para dinero a nivel de céntimo el
resultado es exacto. En modo batch Alembic recrea las tablas y copia los datos.

Revision ID: 41a968cc7c88
Revises: dcc0399a6e5a
Create Date: 2026-07-28 12:25:13.160151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41a968cc7c88'
down_revision: Union[str, None] = 'dcc0399a6e5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('budget_limit',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('recurring_transactions', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('recurring_transactions', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('budget_limit',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
