"""tabla de alertas de precio

Revision ID: 5f6dc9281ea7
Revises: 1fedfba2a876
Create Date: 2026-07-31 23:06:29.993903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f6dc9281ea7'
down_revision: Union[str, None] = '1fedfba2a876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('por_encima', 'por_debajo', 'caida_diaria', name='tipoalerta'), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('ultimo_disparo', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alertas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alertas_asset_id'), ['asset_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alertas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alertas_asset_id'))

    op.drop_table('alertas')
    # ### end Alembic commands ###
