"""tabla de pesos objetivo

Revision ID: e0a5c7f2e8c6
Revises: 5f6dc9281ea7
Create Date: 2026-08-01 03:09:15.396422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0a5c7f2e8c6'
down_revision: Union[str, None] = '5f6dc9281ea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pesos_objetivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('porcentaje', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pesos_objetivo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pesos_objetivo_asset_id'), ['asset_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pesos_objetivo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pesos_objetivo_asset_id'))

    op.drop_table('pesos_objetivo')
    # ### end Alembic commands ###
